pdd/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tickets/', include("tickets.urls", namespace='tickets')),
    # url(r'^tinymce/', include('tinymce.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tickets/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from .views import (
    ErrorsReportView,
    ExamReportView,
    ExamTemplateView,
    Errors,
    QuestionDetailView,
    MarathonTemplateView,
    MarathonReportView,
    TicketListView,
    TicketReportView,

    toggle_Timer,
    start_Timer,
    # timer_Report,

    ThemeListView,
    ThemeReportView,
    pdddataAdd,
    pdddataClear,
    )


urlpatterns = [
    url(r'^$', TicketListView.as_view(), name='ticket_list'),
    url(r'^(?P<pk>[\d-]+)/$', QuestionDetailView.as_view(), name='question_detail'),
    url(r'^errors/$', Errors.as_view(), name='errors'),
    url(r'^exam/$', ExamTemplateView.as_view(), name='exam'),
    url(r'^marathon/$', MarathonTemplateView.as_view(), name='marathon'),
    url(r'^theme/$', ThemeListView.as_view(), name='theme_list'),

    url(r'^(?P<pk>[\d-]+)/pdddataAdd/$', pdddataAdd, name='pdddataAdd'),
    url(r'^clear/$', pdddataClear, name='pdddataClear'),
    url(r'^start_timer/$', start_Timer, name='start_Timer'),
    url(r'^toggle_timer/$', toggle_Timer, name='toggle_Timer'),  
    # url(r'^timer_report/$', timer_Report, name='timer_Report'),

    url(r'^errors_report/$', ErrorsReportView.as_view(), name='errors_report'),
    url(r'^exam_report/$', ExamReportView.as_view(), name='exam_report'),
    url(r'^marathon_report/$', MarathonReportView.as_view(), name='theme_report'),  
    url(r'^ticket_report/$', TicketReportView.as_view(), name='ticket_report'),
    url(r'^theme_report/$', ThemeReportView.as_view(), name='theme_report'),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/includes/_pdd_nav.html
<p class="text-center">
  <a class="btn btn-default" role="button" href="{% url 'tickets:pdddataClear'%}"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Очистить историю</a>
</p>

<ul class="nav nav-tabs nav-justified">
  {% url 'tickets:exam' as exam %}
  <li role="presentation" class="{% if nav_tab == 'exam' or current_url == exam %}active{% else %}nav-none-active-tab{% endif %}">
    <a class="pdd-nav" href="{% url 'tickets:exam'%}" style="padding-left: 13px; padding-right: 12px;"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> Экзамен</a>
  </li>
  
  {% url 'tickets:ticket_list' as tickets %}
  <li role="presentation"  class="{% if nav_tab == 'ticket' or current_url == tickets %}active{% else %}nav-none-active-tab{% endif %}">
    <a href="{% url 'tickets:ticket_list'%}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Билеты</a>
  </li>

  {% url 'tickets:theme_list' as theme %}
  <li role="presentation" class="{% if nav_tab == 'theme' or current_url == theme %}active{% else %}nav-none-active-tab{% endif %}">
    <a href="{% url 'tickets:theme_list'%}" style="padding-left: 18px; padding-right: 17px;"><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span> Темы</a>
  </li>

  {% url 'tickets:marathon' as marathon %}
  <li role="presentation" class="{% if nav_tab == 'marathon' or current_url == marathon %}active{% else %}nav-none-active-tab{% endif %}">
    <a href="{% url 'tickets:marathon'%}" style="padding-left: 7px; padding-right: 7px;"><span class="glyphicon glyphicon-plane" aria-hidden="true"></span> Марафон 800</a>
  </li>

  {% url 'tickets:errors' as errors %}
  <li role="presentation" class="{% if nav_tab == 'errors' or current_url == errors %}active{% else %}nav-none-active-tab{% endif %}">
    <a href="{% url 'tickets:errors' %}"><span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span> Мои ошибки</a>
  </li>

  
  <!-- <li role="presentation" class='hidden-xs'><a href="#">ПДД виджет</a></li> -->
</ul>
<!-- {{nav_tab}} -->

templates/base/includes/_star_progress_bar.html
<div class="row">
<br>

	<div class="star-line {% if nav_tab == 'theme' or nav_tab == 'marathon'%} star-line-marathon-theme-error{% endif %}" >
	{% for star in stars %}		
		<span class="glyphicon glyphicon-star" aria-hidden="true" style="color:{{ star }}"></span>
	{% endfor %}

	{% for star in grey_stars %}
	<span class="grey-star-{{ forloop.counter }}">
		<span class="glyphicon glyphicon-star" aria-hidden="true" ></span>
	</span>
		
	{% endfor %}
	
	</div>
</div>