pdd/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tickets/', include("tickets.urls", namespace='tickets')),
    # url(r'^tinymce/', include('tinymce.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tickets/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from .views import (
    ErrorsReportView,
    ExamReportView,
    ExamTemplateView,
    Errors,
    QuestionDetailView,
    MarathonTemplateView,
    MarathonReportView,
    TicketListView,
    TicketReportView,

    toggle_Timer,
    start_Timer,
    # timer_Report,

    ThemeListView,
    ThemeReportView,
    pdddataAdd,
    pdddataClear,
    )


urlpatterns = [
    url(r'^$', TicketListView.as_view(), name='ticket_list'),
    url(r'^(?P<pk>[\d-]+)/$', QuestionDetailView.as_view(), name='question_detail'),
    url(r'^errors/$', Errors.as_view(), name='errors'),
    url(r'^exam/$', ExamTemplateView.as_view(), name='exam'),
    url(r'^marathon/$', MarathonTemplateView.as_view(), name='marathon'),
    url(r'^theme/$', ThemeListView.as_view(), name='theme_list'),

    url(r'^(?P<pk>[\d-]+)/pdddataAdd/$', pdddataAdd, name='pdddataAdd'),
    url(r'^clear/$', pdddataClear, name='pdddataClear'),
    url(r'^start_timer/$', start_Timer, name='start_Timer'),
    url(r'^toggle_timer/$', toggle_Timer, name='toggle_Timer'),  
    # url(r'^timer_report/$', timer_Report, name='timer_Report'),

    url(r'^errors_report/$', ErrorsReportView.as_view(), name='errors_report'),
    url(r'^exam_report/$', ExamReportView.as_view(), name='exam_report'),
    url(r'^marathon_report/$', MarathonReportView.as_view(), name='theme_report'),  
    url(r'^ticket_report/$', TicketReportView.as_view(), name='ticket_report'),
    url(r'^theme_report/$', ThemeReportView.as_view(), name='theme_report'),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tickets/views.py
# coding=utf-8

import re

from django.http import Http404, HttpResponse, HttpResponseNotAllowed
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import (
    DetailView, ListView, TemplateView,
    )
from django.views.decorators.http import require_POST

from .models import (
    Ticket,
    Question,
    Theme,
    Choice,
    )
from pass_data import Stars, Report, ErrorsPdd, Timer
from generic.mixins import PddContextMixin


class TicketListView(PddContextMixin, TemplateView):
    template_name = 'tickets/ticket_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(TicketListView, self).get_context_data(*args, **kwargs) 
        report = Report(self.request).report
        tickets = Ticket.objects.all()
        ticket_with_result = []
        for ticket in tickets:
            tick_item = report.get( 'ticket_' + str(ticket.id), {} )
            tick_item[ 'tick_number' ] = ticket.tick_number
            tick_item[ 'first_question_num' ] = ticket.get_first_question_num()
            tick_item[ 'is_whole_ticket' ] = ticket.is_whole_ticket

            ticket_with_result.append(tick_item)
        context['tickets'] = ticket_with_result
        self.request.session['nav_tab'] = 'ticket'
        stars = Stars(self.request)
        stars.clear()       
        return context


class ThemeListView(PddContextMixin, TemplateView):
    template_name = 'tickets/theme_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ThemeListView, self).get_context_data(*args, **kwargs)
        report = Report(self.request).report
        themes = Theme.objects.all()
        theme_with_result = []
        for theme in themes:
            theme_item = report.get( 'theme_' + str(theme.id), {} )
            theme_item[ 'theme_name' ] = theme.name
            theme_item[ 'first_question_num' ] = theme.get_first_question_num()

            theme_item[ 'ticket_number' ] = len(theme.questions.all())
            theme_with_result.append(theme_item)
        context['themes'] = theme_with_result
        self.request.session['nav_tab'] = 'theme'
        stars = Stars(self.request)
        stars.clear()
        return context


class QuestionDetailView(DetailView):
    model = Question
    template_name = 'tickets/question_detail.html'  
    context_object_name = 'question'

    def get_context_data(self, *args, **kwargs):
        context = super(QuestionDetailView, self).get_context_data(*args, **kwargs)
        stars = Stars( self.request )
        timer = Timer( self.request)
        context['stars'] = stars.stars
        nav_tab = self.request.session.get('nav_tab')
        context['nav_tab'] = nav_tab
        if nav_tab == 'ticket':
            star_num = len(self.object.ticket.questions.all())
        elif nav_tab == 'theme':           
            star_num = len(self.object.theme.questions.all())
        else:
            star_num = self.request.session['grey_stars']
        n = star_num - len(stars.stars)  
        context['grey_stars'] = [None for i in range(n)]
        context['minutes'] = timer.timer.get('current_timer_min', '00')
        context['seconds'] = timer.timer.get('current_timer_sec', '00')
        return context


@require_POST
def pdddataAdd(request, pk):
     # pk - pk вопроса
     
    def count_red_in_exam_errors( stars_list ):
        res = 0
        for i in stars_list:
            if i == 'red':
                res += 1
        return res


    def get_additional_questions( question, question_id_list ):
        theme_id = question.theme.id
        q = Question.objects.values_list( 'theme', 'id', )
        all_question_with_current_theme = []
        for item in q:
            if item[ 0 ] == theme_id:
                all_question_with_current_theme.append( item[ 1 ] )

        set_get_additional_questions = set( all_question_with_current_theme ) - set( question_id_list )
        if len( set_get_additional_questions ) < 5:
            all_question_id_list = Question.objects.values_list( 'id', flat = True)

            unused_questions = set(all_question_id_list) - set_get_additional_questions - set( question_id_list )
            unused_questions_list = list( unused_questions )[ : 5 ]
            additional_questions_list = list( set_get_additional_questions )
            additional_questions_list.extend( unused_questions_list )
            return additional_questions_list[ : 5 ] 
        else:
            return list(set_get_additional_questions)[ : 5 ]

    
    nav_tab = request.session['nav_tab']
    if nav_tab == 'exam':
        question_id_list = request.session['exam_question_list']
        stars, report, timer = (
                Stars(request),
                Report(request),
                Timer(request),
            )
        question = get_object_or_404( Question, pk = pk )
        user_choice = int(request.POST['choice'])
        right_choice = question.get_right_choice
        pk_index = question_id_list.index( int(pk) )
        timer.timer['current_timer_min'] = request.POST['countup-min']
        timer.timer['current_timer_sec'] = request.POST['countup-sec']

    # если ответ не правильный 
        if not user_choice == right_choice:
            stars.add_data(question, data = 'red')
            # подсчитываем ошибки:
            red_stars = count_red_in_exam_errors( stars.stars )
            
            # экзамен сдан           
            if pk_index == 24  and red_stars == 1:
                report.add_data( 'exam',  24, 1 )               
                timer.stop()
                request.session['exam_result'] = 'Экзамен сдан!'
                return redirect( '/tickets/exam_report' )
            elif pk_index == 29  and red_stars == 2:
                report.add_data( 'exam',  28, 2 )
                timer.stop()
                request.session['exam_result'] = 'Экзамен сдан!'
                return redirect( '/tickets/exam_report' )
            # экзамен не сдан  
            elif pk_index < 20  and red_stars == 3:
                report.add_data( 'exam',  len( stars.stars ) - 3, 3 )
                timer.stop()
                request.session['exam_result'] = 'Экзамен не сдан. Слишком много ошибок!'
                return redirect( '/tickets/exam_report' )
            elif pk_index >= 20  and red_stars == 2:
                report.add_data( 'exam',  len( stars.stars ) - 3, 3 )
                timer.stop()
                request.session['exam_result'] = 'Экзамен не сдан. Слишком много ошибок!'
                return redirect( '/tickets/exam_report' )
            # добавление 5ти вопросов и продолжение экзамена
            elif(len(question_id_list) == 20 and red_stars == 1) or (len(question_id_list) == 25 and red_stars == 2):

                additional_question_list = get_additional_questions( question, question_id_list )
                question_id_list.extend(additional_question_list)
                request.session['exam_question_list'] = question_id_list
                request.session['grey_stars'] += 5
                next_question_id = question_id_list[ pk_index + 1 ]
                return redirect( 'tickets:question_detail', str(next_question_id) )    
            else:
                pass
        # если ответ правильный 
        else:
            stars.add_data(question, data = 'green')
            red_stars = count_red_in_exam_errors( stars.stars )
            # ответ правильный, экзамен сдан:
            if pk_index == 19  and red_stars == 0:
                report.add_data( 'exam',  20, 0 )
                timer.stop()
                request.session['exam_result'] = 'Экзамен сдан!'
                return redirect( '/tickets/exam_report' )
            elif pk_index == 24  and red_stars == 1:
                report.add_data( 'exam',  24, 1 )
                timer.stop()
                request.session['exam_result'] = 'Экзамен сдан!'
                return redirect( '/tickets/exam_report' )
            elif pk_index == 29  and red_stars == 2:
                report.add_data( 'exam',  29, 2 )
                timer.stop()
                request.session['exam_result'] = 'Экзамен сдан!'
                return redirect( '/tickets/exam_report' )
            # ответ правильный, экзамен продолжается:
            else:
                next_question_id = question_id_list[ pk_index + 1 ]
                return redirect('tickets:question_detail', str(next_question_id))

    if nav_tab == 'ticket' or nav_tab == 'theme' or nav_tab == 'marathon' or nav_tab == 'errors' :
        stars, report, errors , timer = (
            Stars(request),
            Report(request),
            ErrorsPdd(request),
            Timer(request),
        )

        question = get_object_or_404( Question, pk = pk )
        user_choice = int(request.POST['choice'])
        right_choice = question.get_right_choice
        question_id = unicode( question.id )

        if not user_choice == right_choice:
            wrong_text = get_object_or_404( Choice, pk = user_choice ).choice_text
            right_text = get_object_or_404( Choice, pk = right_choice ).choice_text
            errors.add_data( question_id, wrong_text, right_text )
            stars.add_data(question, data = 'red')
        else:
            if question_id in errors.errors.keys():
                errors.remove_question_data( question_id )
            stars.add_data(question, data = 'green')

    
    if nav_tab == 'ticket':
        question_id_list = question.get_question_id_list_in_ticket()
    elif nav_tab == 'theme':
        question_id_list = question.get_question_id_list_in_theme()
    elif nav_tab == 'marathon':
        question_id_list = request.session['marathon_list']
        timer.timer['current_timer_min'] = request.POST['countup-min']
        timer.timer['current_timer_sec'] = request.POST['countup-sec']

    elif nav_tab == 'errors':
        errors_list = request.session['errors_list']
        try:

tickets/templates/tickets/errors.html
{% extends "base/__base.html" %}


{% block content %}
<br>
<div class="alert alert-info" role="alert">
	<h2 class="text-primary text-center">Работа над ошибками:</h2>
	<p class="text-center" >В данном разделе собираются ваши ошибки, которые вы сделали решая <strong>разделы «билеты, темы и марафон»</strong>. {% if pk %}Для того, чтобы исправить свои ошибки, нажмите на кнопку ниже.{% endif %}</p>

	<p class="text-center" style='bac'>Сейчас у вас {% if errors %}<span class="badge" style='background-color:red;'>{{ errors }}</span>{% else %} <strong>нет</strong>{% endif %} ошибок: </p>
</div>

<br>
{% if pk %}
<p class="text-center">
	<a class="btn btn-primary" href="{% url 'tickets:question_detail' pk %}" role="button">Начать работу над ошибками</a>
</p>
<br>
<div class="alert alert-success" role="alert">
	<p>
		Исправление ошибок в разделе «Ошибки» не влияет на общую статистику в блоке «билеты». Например, Вы решили первый билет и сделали в нём 3 ошибки, в блоке с билетом вы можете наблюдать 17 правильных и 3 неправильных. Зайдя в раздел «ошибки» Вы видите тоже 3 ошибки, прорешав и исправив их, они исчезнут только в разделе «ошибки». В вкладке «билеты» по прежнему Вы будете наблюдать, что в первом билете у вас допущено 3 ошибки. Это сделано для визуальной ориентации, чтобы вы понимали где вы допускали ошибки.
	</p>
</div>

{% endif %}
{% endblock content %}

tickets/templates/tickets/errors_report.html
{% extends "base/__base.html" %}

{% block content %}


<h2 class="text-primary text-center">Ваш результат:</h2>

<p class="text-center" style='bac'>Правильных ответов: <span class="badge" style='background-color:green;'>{{ right_ans }}</span></p>
<p class="text-center">Сделали ошибок: <span class="badge" style='background-color:red;'>{{ wrong_ans }}</span></p>

{% endblock content %}

tickets/templates/tickets/exam.html
{% extends "base/__base.html" %}

{% block content %}
<br>
<div class="alert alert-success" role="alert">
	<p>Итак, раз вы на страницах моего сервиса, то дайте я попробую угадать, вы наверно собираетесь обзавестись правами, а может просто решили освежить свои знания в <strong>теории по ПДД</strong>? Так или иначе мой сервис будет вам полезен в любом случае!!!</p>
	<p>Сейчас вы находитесь на вкладке Экзамен, если вы уже готовы попытаться пройти тестирование на знание <strong>правил дорожного движения</strong>, то жмякайте кнопку ПОЕХАЛИ!</p>
</div>	
<p class="text-center"><strong>На экзамен даётся 20 минут. </strong></p>
<p class="text-center"><strong>Внимательно читайте каждый вопрос и все варианты ответов.</strong></p>
<p class="text-center"><strong>Не торопитесь. Удачи!</strong></p>
<p class="text-center">
	<a class="btn btn-primary" href="{% url 'tickets:start_Timer' %}" role="button">ПОЕХАЛИ!</a>
</p>
{% endblock content %}

tickets/templates/tickets/exam_report.html
{% extends "base/__base.html" %}

{% block content %}

<h2 class="text-primary text-center">{% if not time_for_test.2 %}Экзамен не сдан</h2><h2 class="text-primary text-center">Вы не уложтлись в 20 минут{% else %}{{ exam_result }}{% endif %}</h2>
<h3 class="text-primary text-center">Ваш результат:</h3>
<p class="text-center" style='bac'>Правильных ответов: <span class="badge" style='background-color:green;'>{{ right_ans }}</span></p>
<p class="text-center">Сделали ошибок: <span class="badge" style='background-color:red;'>{{ wrong_ans }}</span></p>

<p class="text-center">Время выполнения: <span class="badge" style='background-color:blue;'>{% if not time_for_test.0 %}{{ time_for_test.0 }} мин., {% endif %}{{ time_for_test.1 }} сек.  </span></p>
<p class="text-center">
	<a class="btn btn-default" href="{% url 'tickets:exam' %}" role="button">Попробовать еще раз</a>
</p>

{% endblock content %}

tickets/templates/tickets/marathon.html
{% extends "base/__base.html" %}

{% block content %}
<br>
<div class="alert alert-info" role="alert">
	<p>Итак, вы выучили билеты, прошли тестовый экзамен, самое время проверить себя в боевом режиме.</p>
	<p>Предлагаю вам пройти все 800 вопросов. После того как вы пройдёте тест на 800 вопросов система покажет вам готовы вы к экзамену в ГАИ или нет.</p>
	<p>В режиме «Марафон 800» надо ответить на 800 вопросов. Если вы сделаете более 20 ошибок система скажет, что вы еще не готовы к экзамену в ГАИ.</p>
	<p>В режиме «Марафон 800» подсказки до момента пока вы не ответили на вопрос не работают.</p>
	<p>В режиме «Марафон 800» после прохождения теста не показывается блок работа над ошибками.</p>
</div>
<p class="text-center">Марафон еще не пройден</p>
<p class="text-center">
	<a class="btn btn-primary" href="{% url 'tickets:start_Timer' %}" role="button">Начать "Марафон 800"</a>
</p>

{% endblock content %}

И

tickets/templates/tickets/marathon_report.html
{% extends "base/__base.html" %}

{% block content %}
<!-- {{ timer }} -->

<div class="alert alert-success" role="alert">
	<h2 class="text-primary text-center">Поздравляем! Вы прошли марафон!</h2>
	<h2 class="text-primary text-center">Ваш результат:</h2>

	<p class="text-center" style='bac'>Правильных ответов: <span class="badge" style='background-color:green;'>{{ right_ans }}</span></p>
	<p class="text-center">Сделали ошибок: <span class="badge" style='background-color:red;'>{{ wrong_ans }}</span></p>
	{% if time_for_test %}<p class="text-center">Время выполнения:  {{ time_for_test.0 }} мин., {{ time_for_test.1 }} сек.  </p>{% endif %}
</div>


{% endblock content %}

tickets/templates/tickets/question_detail.html
{% extends "base/__base.html" %}
{% load static %}

{% block progressbar %}
{% include 'base/includes/_star_progress_bar.html' %}
{% endblock progressbar %}

{% block content %}
<div id='minutes' class="hidden">{{ minutes }}</div>
<div id='seconds' class="hidden">{{ seconds }}</div>

<form  action="{% url 'tickets:pdddataAdd' question.id %}" method="post">
	{% if nav_tab == 'marathon' or nav_tab == 'exam' %}
	<div class="text-center countup">
			<input id="countup-min" class="countup" name='countup-min' type="text" value="{{ minutes }}"> :
			<input id="countup-sec" class="countup" name='countup-sec' type="text" value="{{ seconds }}">      
		</div>
		
	{% endif %}
	<br>

	{% if not nav_tab == 'exam' %}
		<div class="row">
		<div class="col-xs-4 text-center"><button type="button" class="btn btn-primary btn-xs">Билет №{{ question.ticket.id }}</button></div>

		{% if nav_tab == 'marathon' %}
			
			<div class="col-xs-4 text-center">
				<input id="pauseButton" type="button" value="Пауза">
				<input id="resumeButton" type="hidden" value="Продолжить">
			</div>
		{% endif %}


		<div class="col-xs-4 text-center"><button type="button" class="btn btn-info btn-xs">Вопрос №{{ question.question_number }}</button></div>
		</div>
	{% endif %}
	
	<br>
	<img class="img-responsive" src="{% if question.image %}{{ question.image.url }}{% else %}{% static 'img/question_without_img.png' %}{% endif %}">
	<br>
	<p class="text-center"><strong>{{ question.question }}</strong></p>


	
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
	<div class="pdd-question-answer-block">
			<input class="pdd-ticket-input {% if choice.choice_status %}right-ans{% else %}wrong-ans{% endif %}" id="choice{{ forloop.counter }}" type="radio" name="choice" value="{{ choice.id }}" />
			<label class="pdd-label {% if choice.choice_status %}right-ans{% else %}wrong-ans{% endif %}" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>		
		<br />	
	</div>
	   
	    
	{% endfor %}
	<br><div class="row" >
			<div class="col-xs-6 text-left">
				<input class="btn btn-primary pdd-check-button" type="button" value="Проверить">		
				<input type="submit" class="btn btn-primary pdd-next-button" style="display:none"  value="Дальше">
			</div>
			{% if not nav_tab == 'exam' and question.tip %}
			<div class="col-xs-6 text-center">
				<input id='tip-tog' class="btn btn-warning" type="button" value="Подсказка">
			</div>
			{% endif %}
		</div>
		<div class="row" style="margin-top: 20px;">
			<div class="col-xs-12">
				<div id="tip-content" class="alert alert-warning" role="alert">{{ question.tip|safe }}</div>
			</div>
		</div>	
	</form>

{% endblock content %}

tickets/templates/tickets/theme_list.html
{% extends "base/__base.html" %}

{% block content %}
<br>
<table class="table">
	<thead>
		<tr>
			<th>Тема</th>
			<th class='hidden-xs'>Вопросы</th>
			<th>Результат</th>
		</tr>
	</thead>
	<tbody>
	{% for theme_item in themes %}

		{% if theme_item.first_question_num %}
		<tr class="theme-list-item" data-href="{% url 'tickets:question_detail' theme_item.first_question_num %}">
			<td><a href="{% url 'tickets:question_detail' theme_item.first_question_num %}">{{ theme_item.theme_name }}</a></td>
			<td class='hidden-xs'><a href="{% url 'tickets:question_detail' theme_item.first_question_num %}">{{ theme_item.ticket_number }}</a></td>
			{% if theme_item.right or theme_item.wrong %}
			<td>
				<div>
					<small>Правильно:  <span class="badge" style="background-color:green; font-size:10px">{{ theme_item.right }}</span>
					</small>
				</div>
				<div>
					<small>Не правильно:  <span class="badge" style="background-color:red; font-size:10px">{{ theme_item.wrong }}</span></small>
				</div>
			</td>
				{% else %}
			<td><a href="{% url 'tickets:question_detail' theme_item.first_question_num %}">Не пройдено</a></td>	
				{% endif %}	
			
		</tr>
		{% endif %}
	{% endfor %}
	</tbody>
</table>
{% endblock content %}

tickets/templates/tickets/theme_report.html
{% extends "base/__base.html" %}


{% block content %}


<h2 class="text-primary text-center">Ваш результат:</h2>
<h4 class="text-primary text-center">Вы прошли тему: {{ theme_name }}</h4>

<p class="text-center" style='bac'>Правильных ответов: <span class="badge" style='background-color:green;'>{{ right_ans }}</span></p>
<p class="text-center">Сделали ошибок: <span class="badge" style='background-color:red;'>{{ wrong_ans }}</span></p>

<p class="text-center"><a class="btn btn-primary" href="{% url 'tickets:theme_list' %}" role="button">Выбрать другую тему</a></p>

{% for item in data %}

	{% include 'tickets/includes/_report_item.html' %}

{% endfor %}

{% endblock content %}

tickets/templates/tickets/ticket_list.html
{% extends "base/__base.html" %}


{% block content %}
<div class = 'row ticket-list-row'>
<br>

	{% for ticket_item in tickets %}
	
		{% if ticket_item.is_whole_ticket %}
			<!-- {% if ticket_item.first_question_num %} -->

				<div class="col-md-3 col-sm-6 col-ticket">
				<div class="ticket-item" >
					<a href='{% url "tickets:question_detail"  ticket_item.first_question_num %}'>
						<div class="text-center ticket tick-number-{{ ticket_item.tick_number }}">
							Билет № {{ ticket_item.tick_number }}					
						</div>
						{% if ticket_item.right or ticket_item.wrong %}
						<div>
							<small>Правильно:  <span class="badge" style="background-color:green; font-size:10px">{{ ticket_item.right }}</span>
							</small>
						</div>
						<div>
							<small>Не правильно:  <span class="badge" style="background-color:red; font-size:10px">{{ ticket_item.wrong }}</span></small>
						</div>
						{% endif %}
					</a>		
				</div>				

				</div>
			<!-- {% endif %} -->
		{% endif %}
	{% endfor %}

</div>
{% endblock content %}

tickets/templates/tickets/ticket_report.html
{% extends "base/__base.html" %}
{% load static %}

{% block content %}


<h2 class="text-primary text-center">Ваш результат:</h2>
<h4 class="text-primary text-center">Вы прошли билет №{{ ticket_number }}</h4>

<p class="text-center" style='bac'>Правильных ответов: <span class="badge" style='background-color:green;'>{{ right_ans }}</span></p>
<p class="text-center">Сделали ошибок: <span class="badge" style='background-color:red;'>{{ wrong_ans }}</span></p>

<p class="text-center"><a class="btn btn-primary" href="{% url 'tickets:ticket_list' %}" role="button">Выбрать другой билет</a></p>

{% for item in data %}

	{% include 'tickets/includes/_report_item.html' %}

{% endfor %}

{% endblock content %}